---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - vault.yml
  tasks:
    - name: Verify ansible user
      ansible.builtin.command:
        argv:
          - ls
          - /home/ansible
      changed_when: false
    - name: Verify response file
      ansible.builtin.lineinfile:
        path: /home/ansible/ca_directory/response_file
        line: "DXMASTERKEYPASS=REPLACEME1"
        state: absent
      changed_when: false
      register: result
      failed_when: result['found'] != 0
    - name: Verify dsa user
      ansible.builtin.command:  
        argv:
          - id
          - dsa
      changed_when: false
    - name: Verify that CA Directory is running
      ansible.builtin.command:  
        argv:
          - systemctl
          - status
          - dxserver
      register: dxserver_status
      failed_when: dxserver_status['rc'] != 0
      changed_when: false

    - name: Copy test users ldif
      ansible.builtin.template:
        src: "../../templates/testusers.ldif"
        dest: "/home/ansible/ca_directory/testusers.ldif"
        owner: ansible
        group: adm
        mode: '0700'
    - name: Add some test entries
      ansible.builtin.command: 
        argv:
          - ldapadd
          - -H
          - "ldap://{{ inventory_hostname }}:4000"
          - -D
          - "cn=adm,ou=People,o=cra"
          - -w
          - '{{ LDAP_ADMIN_PASSWORD }}'
          - -f
          - /home/ansible/ca_directory/testusers.ldif
      register: user_result
      changed_when: true
    - name: Lookup the new user
      ansible.builtin.command:
        argv:
          - ldapsearch
          - -H
          - "ldap://{{ inventory_hostname }}:4000"
          - -x
          - -b 
          - 'cn=bob,ou=People,o=cra'
          - email
      changed_when: false
      register: search_result
      failed_when: "'email: bob@cra-arc.gc.ca' not in search_result.stdout"

    - name: Verify that DSA is started
      ansible.builtin.command: 
        argv:
          - dxserver
          - status
      become_user: dsa
      become_flags: "-i"
      become: true
      register: dsa_status
      failed_when: "'crausers started' not in dsa_status.stdout"
      changed_when: false
    - name: Verify admin.ldif file
      ansible.builtin.lineinfile:
        path: /home/ansible/ca_directory/admin.ldif
        line: "userPassword: LDAP_ADMIN_PASSWORD_HASH_REPLACE_ME"
        state: absent
      changed_when: false
      register: result
      failed_when: result['found'] != 0
    - name: Verify that Admin user is there
      ansible.builtin.command: 
        argv: 
          - ldapsearch
          - -H
          - "ldap://{{ inventory_hostname }}:4000"
          - -x
          - -b 
          - 'cn=admin,ou=People,o=cra'
      changed_when: false
      register: search_result
      failed_when: search_result["rc"] == 32
