---
- name: Check if Data Store exists
  become: true
  become_user: dsa
  become_flags: "-i"
  ansible.builtin.shell: "dxserver status | grep crausers"
  register: datastore
  ignore_errors: true
  changed_when: false

- name: Create and start Data Store
  become: true
  become_user: dsa
  become_flags: "-i"
  when: datastore['rc'] != 0
  block:
    - name: Create Data Store
      ansible.builtin.command:
        chdir: /disk/apps/directory/dxserver/bin
        argv:
          - ./dxnewdsa
          - crausers
          - 4000
          - ou=People,o=cra
      changed_when: datastore['rc'] == 0
    - name: Start Data Store
      ansible.builtin.command: dxserver start crausers
      changed_when: datastore['rc'] == 0

- name: Check if Service Exists
  ansible.builtin.stat: 
    path: /etc/init.d/firewalld
  register: service_status
- name: Check firewall
  when: service_status.stat.exists
  block:
  - name: Make sure firewall is running
    ansible.builtin.service:
      name: firewalld
      state: started
  - name: Add Firewall rules to accept connection
    ansible.posix.firewalld:
      permanent: true
      immediate: true
      port: 4000/tcp
      state: enabled